Repository MISP/MISP, pull requests merged in 2019-05, with the labels that each got.

#4534 Zoidberg's son: Update system
  app/Console/Command/AdminShell.php
  app/Console/Command/ServerShell.php
  app/Controller/AppController.php
  app/Controller/Component/ACLComponent.php
  app/Controller/ServersController.php
  app/Model/AppModel.php
  app/Model/Server.php
  app/View/Elements/Flash/error.ctp
  app/View/Elements/healthElements/diagnostics.ctp
  app/View/Servers/ondemand_action.ctp
  app/View/Servers/update_progress.ctp
  app/webroot/css/update_progress.css
  app/webroot/js/update_progress.js
Labels: enhancement, topic:UI

#4595 rpz: make NXDOMAIN default
  app/Model/Server.php
Labels: signed-off:adulau

#4647 Match EDNS packets with snort rules
  app/Lib/Export/NidsExport.php
Labels: topic:api

#4638 fix: On-Demand Action missed side menu fixed
  app/View/Servers/ondemand_action.ctp
Labels: not-reviewed

#4639 GRANTs updated to DBUSER_MISP instead of DBNAME.
  INSTALL/INSTALL.sh
Labels: not-reviewed

#4683 fix: [freetext import] Fixed shadow attribute import
  app/Model/Event.php
Labels: from:training
