Repository MISP/MISP, pull requests merged in 2019-06, with the labels that each got.

#4672 Merge attributes into objects
  app/Controller/AttributesController.php
  app/Controller/Component/ACLComponent.php
  app/Controller/ObjectsController.php
  app/Model/Attribute.php
  app/Model/MispObject.php
  app/Model/ObjectTemplate.php
  app/View/Elements/eventattributetoolbar.ctp
  app/View/Objects/group_attributes_into_object.ctp
  app/View/Objects/propose_objects_from_attributes.ctp
  app/webroot/js/misp.js
Labels: not-reviewed

#4635 Galaxy matrix improvements
  app/Controller/EventsController.php
  app/Controller/GalaxyClustersController.php
  app/Controller/UsersController.php
  app/Lib/Export/AttackExport.php
  app/Model/Attribute.php
  app/Model/AttributeTag.php
  app/Model/EventTag.php
  app/Model/Galaxy.php
  app/View/Elements/view_galaxy_matrix.ctp
  app/View/Helper/TextColourHelper.php
  app/View/Layouts/default.ctp
  app/View/Users/statistics_galaxymatrix.ctp
  app/webroot/css/attack_matrix.css
  app/webroot/css/main.css
  app/webroot/js/attack_matrix.js
  app/webroot/js/misp.js
Labels: not-reviewed

#4734 fix: [installer] added missing python zmq lib
  INSTALL/INSTALL.tpl.sh
Labels: topic:install

#4674 strict typing - snuffleupagus tests
  app/Controller/AppController.php
Labels: not-reviewed

#4769 fix: [js] fixes #4678 and javascript errors
  app/webroot/js/misp.js
Labels: not-reviewed

#4570 Related event ui
  app/Controller/EventsController.php
  app/View/Elements/Events/View/related_event.ctp
  app/View/Events/view.ctp
  app/View/Feeds/preview_event.ctp
  app/View/Servers/preview_event.ctp
Labels: not-reviewed, topic:23:59
