Repository MISP/MISP, pull requests merged in 2019-11, with the labels that each got.

#5002 Revised update process
  .travis.yml
  app/Console/Command/AdminShell.php
  app/Console/dumpDBSchema.sh
  app/Console/worker/start.sh
  app/Console/worker/start_dynamic.sh
  app/Controller/AppController.php
  app/Controller/Component/ACLComponent.php
  app/Controller/JobsController.php
  app/Controller/ServersController.php
  app/Model/AppModel.php
  app/Model/Log.php
  app/Model/Server.php
  app/View/Elements/genericElements/IndexTable/headers.ctp
  app/View/Elements/genericElements/IndexTable/index_table.ctp
  app/View/Elements/healthElements/db_schema_status.ctp
  app/View/Elements/healthElements/diagnostics.ctp
  app/View/Servers/ondemand_action.ctp
  app/View/Servers/update_progress.ctp
  app/webroot/css/main.css
  app/webroot/css/taskScheduler.css
  app/webroot/css/update_progress.css
  app/webroot/js/misp.js
  app/webroot/js/taskScheduler.js
  app/webroot/js/update_progress.js
  db_schema.json
  docs/generic/MISP_CAKE_init.md
Labels: enhancement, not-reviewed, update

#5381 Feature meta search
  app/Model/Attribute.php
  app/Model/Event.php
  app/Model/GalaxyCluster.php
  app/Model/Organisation.php
Labels: enhancement, usability

#4917 Allow pushing sightings with perm_sighting
  INSTALL/MYSQL.sql
  INSTALL/POSTGRESQL-data-initial.sql
  INSTALL/POSTGRESQL-structure.sql
  app/Console/Command/EventShell.php
  app/Console/Command/ServerShell.php
  app/Controller/Component/ACLComponent.php
  app/Controller/Component/RestResponseComponent.php
  app/Controller/EventsController.php
  app/Controller/ServersController.php
  app/Controller/SightingsController.php
  app/Model/AppModel.php
  app/Model/Event.php
  app/Model/Server.php
  app/Model/Sighting.php
  app/View/Servers/add.ctp
  app/View/Servers/edit.ctp
  app/View/Servers/index.ctp
  app/View/Servers/pull.ctp
Labels: not-reviewed

#5404 Added more Organisation statistics
  app/Controller/UsersController.php
  app/Model/User.php
  app/View/Users/statistics_orgs.ctp
Labels: topic:UI
