Repository MISP/MISP, pull requests merged in 2020-04, with the labels that each got.

#5574 fix: [internal] HTML code in view_event_distribution_graph
  app/View/Elements/view_event_distribution_graph.ctp
Labels: WaitingAnswer, not-reviewed, waitingApprovalFromThor

#5606 fix: [UI] Proper object table header when includeRelatedTags
  app/View/Elements/Events/View/row_object.ctp
Labels: WaitingAnswer, not-reviewed, waitingApprovalFromThor

#5816 Modify the default parsing settings of Phishtank feed
  app/files/feed-metadata/defaults.json
Labels: not-reviewed

#5561 chg: [internal] Cache result of AppController::_isRest method
  app/Controller/AppController.php
Labels: WaitingAnswer, waitingApprovalFromThor

#5207 fix: [internal] Just site admin can force when saving freetext
  app/Controller/EventsController.php
Labels: WaitingAnswer, waitingApprovalFromThor
