Repository MISP/MISP, pull requests merged in 2022-05, with the labels that each got.

#8367 BEAM SOC MISP Community added.
  app/files/community-metadata/defaults.json
Labels: T: community-meta

#8422 Fixed a logic error in Tag::quickEdit()
  app/Model/Tag.php
Labels: T: bug

#8423 Accessibility: added missing 'title' attributes in the Galaxies index
  app/View/Galaxies/index.ctp
Labels: UI
